import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-50 dark:bg-gray-800 min-h-screen flex flex-col">
          <header className="bg-white dark:bg-gray-900 p-4 shadow-md">
            <div className="container mx-auto">
              <h1 className="text-2xl font-bold text-gray-800 dark:text-white">
                File Converter
              </h1>
            </div>
          </header>
          <main className="container mx-auto p-4 flex-grow">{children}</main>
          <footer className="bg-gray-100 dark:bg-gray-700 p-4 text-center text-gray-500 dark:text-gray-400">
            &copy; {new Date().getFullYear()} My File Converter
          </footer>
        </div>
      </body>
    </html>
  );
}
